"""Fetch WHOOP data and save to JSON files + generate whoop_data.js for dashboard."""

import argparse
import asyncio
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import httpx

from whoop_auth import get_valid_token

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
WHOOP_DATA_JS = BASE_DIR / "whoop_data.js"
API_BASE = "https://api.prod.whoop.com/developer/v1"


def _get_client() -> httpx.AsyncClient:
    token = get_valid_token()
    return httpx.AsyncClient(
        base_url=API_BASE,
        headers={"Authorization": f"Bearer {token}"},
        timeout=30.0,
    )


async def fetch_single(client: httpx.AsyncClient, endpoint: str) -> dict:
    """Fetch a single-object endpoint (profile, body measurement)."""
    resp = await client.get(endpoint)
    resp.raise_for_status()
    return resp.json()


async def fetch_paginated(
    client: httpx.AsyncClient,
    endpoint: str,
    start_date: str | None = None,
    end_date: str | None = None,
) -> list[dict]:
    """Fetch all pages from a paginated WHOOP endpoint."""
    all_records = []
    params: dict = {"limit": 25}
    if start_date:
        params["start"] = start_date
    if end_date:
        params["end"] = end_date

    while True:
        resp = await client.get(endpoint, params=params)
        resp.raise_for_status()
        data = resp.json()
        all_records.extend(data.get("records", []))

        next_token = data.get("next_token")
        if not next_token:
            break
        params["nextToken"] = next_token

    return all_records


def _save_json(filename: str, data, fetched_at: str) -> None:
    """Save data to a JSON file in the data directory."""
    DATA_DIR.mkdir(exist_ok=True)
    filepath = DATA_DIR / filename

    if isinstance(data, list):
        payload = {"fetched_at": fetched_at, "count": len(data), "records": data}
    else:
        payload = {"fetched_at": fetched_at, **data}

    filepath.write_text(json.dumps(payload, indent=2))
    print(f"  Saved {filename} ({len(data) if isinstance(data, list) else 1} records)")


def generate_dashboard_js() -> None:
    """Read all JSON data files and generate whoop_data.js for the dashboard."""
    combined = {}
    fetched_at = None

    file_map = {
        "profile": "profile.json",
        "body_measurement": "body_measurement.json",
        "cycles": "cycles.json",
        "recovery": "recovery.json",
        "sleep": "sleep.json",
        "workouts": "workouts.json",
    }

    for key, filename in file_map.items():
        filepath = DATA_DIR / filename
        if filepath.exists():
            data = json.loads(filepath.read_text())
            if fetched_at is None:
                fetched_at = data.get("fetched_at")
            if "records" in data:
                combined[key] = data["records"]
            else:
                # Single-object endpoints (profile, body_measurement)
                obj = {k: v for k, v in data.items() if k != "fetched_at"}
                combined[key] = obj

    if not combined:
        print("  No data files found — skipping whoop_data.js generation")
        return

    combined["fetched_at"] = fetched_at or datetime.now(timezone.utc).isoformat()

    js_content = (
        "// Auto-generated by whoop_pull.py — do not edit\n"
        f"window.WHOOP_DATA = {json.dumps(combined, indent=2)};\n"
    )
    WHOOP_DATA_JS.write_text(js_content)
    print(f"  Generated whoop_data.js for dashboard")


async def pull_all_data(days: int | None = 30) -> None:
    """Pull all WHOOP data and save to JSON files.

    Args:
        days: Number of days to fetch. None means fetch all available data.
    """
    fetched_at = datetime.now(timezone.utc).isoformat()

    # Date range
    end_date = datetime.now(timezone.utc).isoformat()
    start_date = None
    if days is not None:
        start_date = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
        print(f"Fetching WHOOP data for the last {days} days...")
    else:
        print("Fetching all available WHOOP data...")

    async with _get_client() as client:
        # Single-object endpoints (no date filtering)
        print("Fetching profile...")
        try:
            profile = await fetch_single(client, "/user/profile/basic")
            _save_json("profile.json", profile, fetched_at)
        except httpx.HTTPStatusError as e:
            print(f"  Error fetching profile: {e.response.status_code}")

        print("Fetching body measurement...")
        try:
            body = await fetch_single(client, "/user/body/measurement")
            _save_json("body_measurement.json", body, fetched_at)
        except httpx.HTTPStatusError as e:
            print(f"  Error fetching body measurement: {e.response.status_code}")

        # Paginated endpoints with date filtering
        endpoints = {
            "cycles.json": "/cycle",
            "recovery.json": "/recovery",
            "sleep.json": "/activity/sleep",
            "workouts.json": "/activity/workout",
        }

        for filename, endpoint in endpoints.items():
            name = filename.replace(".json", "")
            print(f"Fetching {name}...")
            try:
                records = await fetch_paginated(client, endpoint, start_date, end_date)
                _save_json(filename, records, fetched_at)
            except httpx.HTTPStatusError as e:
                print(f"  Error fetching {name}: {e.response.status_code}")

    # Generate dashboard JS file
    print("Generating dashboard data file...")
    generate_dashboard_js()

    print("\nDone! Open index.html in your browser to view the WHOOP tab.")


def main():
    parser = argparse.ArgumentParser(description="Pull WHOOP data to local JSON files")
    parser.add_argument(
        "--days",
        type=int,
        default=30,
        help="Number of days to fetch (default: 30)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Fetch all available data (no date limit)",
    )
    args = parser.parse_args()

    days = None if args.all else args.days
    asyncio.run(pull_all_data(days))


if __name__ == "__main__":
    main()
